/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.RecyclingCenterEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.InspectionCenterEnterprise;
import Business.Enterprise.MainCenterEnterprise;
import Business.Enterprise.TransportAgencyEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class ManageNetworkJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageNetworkJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    public ManageNetworkJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;

        populateNetworkTable();
    }
    private void populateNetworkTable() {
        DefaultTableModel model = (DefaultTableModel) networkJTable.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            Object[] row = new Object[1];
            row[0] = network.getName();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        networkJTable = new javax.swing.JTable();
        submitJButton = new javax.swing.JButton();
        nameJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        deleteButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setForeground(new java.awt.Color(0, 255, 50));

        networkJTable.setBackground(new java.awt.Color(51, 0, 51));
        networkJTable.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        networkJTable.setForeground(new java.awt.Color(0, 255, 50));
        networkJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(networkJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 780, 160));

        submitJButton.setBackground(new java.awt.Color(51, 0, 51));
        submitJButton.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(0, 255, 50));
        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));

        nameJTextField.setBackground(new java.awt.Color(51, 0, 51));
        nameJTextField.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        nameJTextField.setForeground(new java.awt.Color(0, 255, 50));
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 160, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 50));
        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        backJButton.setBackground(new java.awt.Color(51, 0, 51));
        backJButton.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        backJButton.setForeground(new java.awt.Color(0, 255, 50));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        deleteButton1.setBackground(new java.awt.Color(51, 0, 51));
        deleteButton1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        deleteButton1.setForeground(new java.awt.Color(0, 255, 50));
        deleteButton1.setText("Delete");
        deleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton1ActionPerformed(evt);
            }
        });
        add(deleteButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        boolean nameFlag=false;
        String name = nameJTextField.getText();
        if(name.isEmpty() ) {
            nameFlag=true;
            JOptionPane.showMessageDialog(null, "Please enter network name","Error",JOptionPane.ERROR_MESSAGE);
        }
        if (!nameFlag){
            Network network = system.createAndAddNetwork();
            network.setName(name);
            network.getEnterpriseDirectory().createAndAddEnterprise("Main Center",Enterprise.EnterpriseType.MainCenter);
            network.getEnterpriseDirectory().createAndAddEnterprise("Inspection Center",Enterprise.EnterpriseType.InspectionCenter);
            network.getEnterpriseDirectory().createAndAddEnterprise("Recycling Center",Enterprise.EnterpriseType.RecyclingCenter);
            network.getEnterpriseDirectory().createAndAddEnterprise("Transport Agency",Enterprise.EnterpriseType.TransportAgency);

            for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList())  
            {
                if(enterprise instanceof MainCenterEnterprise)
                {
                   enterprise.getOrganizationDirectory().createOrganization(Organization.Type.StoreChain);
                   enterprise.getOrganizationDirectory().createOrganization(Organization.Type.Donor);
                   enterprise.getOrganizationDirectory().createOrganization(Organization.Type.MainOffice);
                   enterprise.getOrganizationDirectory().createOrganization(Organization.Type.Inventory);
                }
                else if(enterprise instanceof InspectionCenterEnterprise)
                {
                   enterprise.getOrganizationDirectory().createOrganization(Organization.Type.ServiceCenter);
                   enterprise.getOrganizationDirectory().createOrganization(Organization.Type.Technician);
                } 
                else if(enterprise instanceof TransportAgencyEnterprise)
                {
                   enterprise.getOrganizationDirectory().createOrganization(Organization.Type.Transport);
                   enterprise.getOrganizationDirectory().createOrganization(Organization.Type.Driver);
                } 
                else if(enterprise instanceof RecyclingCenterEnterprise)
                {
                   enterprise.getOrganizationDirectory().createOrganization(Organization.Type.Recycling);
                } 
            }
            JOptionPane.showMessageDialog(null, "Network added successfully.");
            nameJTextField.setText("");
            populateNetworkTable();
        }      
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void deleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) networkJTable.getModel();
        
        int selectedRowIndex = networkJTable.getSelectedRow();
        
        if(selectedRowIndex<0) {
            JOptionPane.showMessageDialog(this,"Please select a row to delete.");
            return;
        }

        model.removeRow(selectedRowIndex);
        
        JOptionPane.showMessageDialog(this, "Employee Details deleted");
        
        
    }//GEN-LAST:event_deleteButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton deleteButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTable networkJTable;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
