/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ServiceCenterManagerRole;

import Business.Enterprise.Enterprise;
import Business.Organization.ServiceCenter;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Aadesh Randeria
 */
public class ServiceCenterManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ServiceCenterManagerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private ServiceCenter organization;
    private Enterprise enterprise;
    public ServiceCenterManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, ServiceCenter organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageTechnician = new javax.swing.JButton();
        btnUserAccount = new javax.swing.JButton();
        btnWorkQueue = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("My Work Area - ServiceCenter Manager Role");

        btnManageTechnician.setText("Manage Lab Assistant");
        btnManageTechnician.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageTechnicianActionPerformed(evt);
            }
        });

        btnUserAccount.setText("Manage User Account");
        btnUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserAccountActionPerformed(evt);
            }
        });

        btnWorkQueue.setText("Manage Work Queue");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnManageTechnician)
                    .addComponent(btnUserAccount)
                    .addComponent(btnWorkQueue))
                .addContainerGap(241, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnManageTechnician, btnUserAccount, btnWorkQueue});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(btnManageTechnician)
                .addGap(18, 18, 18)
                .addComponent(btnUserAccount)
                .addGap(18, 18, 18)
                .addComponent(btnWorkQueue)
                .addContainerGap(313, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageTechnicianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTechnicianActionPerformed
        // TODO add your handling code here:
        ManageTechnicianJPanel mlajp = new ManageTechnicianJPanel(userProcessContainer, account, organization, enterprise);
        userProcessContainer.add("ManageTechnicianJPanel", mlajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageTechnicianActionPerformed

    private void btnUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserAccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageTechnician;
    private javax.swing.JButton btnUserAccount;
    private javax.swing.JButton btnWorkQueue;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
